Repository Exove/local-docker, pull requests merged in 2019-12, with the labels that each got.

#120 Issue 118 self updater release tag check fix
  README.md
  docker/scripts/ld.command.self-update.sh
  docker/scripts/self-update.sh
Labels: bug, documentation, enhancement

#117 Issue 116 fix env var expansion for php vars
  .env.example
  .gitignore
  db_dumps/.gitignore
  docker/build/php/7.1/conf.d/95-drupal-development.ini
  docker/build/php/7.2/conf.d/95-drupal-development.ini
  docker/docker-compose.common.yml
  docker/docker-compose.nfs.yml
  docker/docker-compose.skeleton.yml
Labels: bug

#112 Highlight DB dump differences in help texts
  docker/scripts/ld.command.db-backup.sh
  docker/scripts/ld.command.db-dump.sh
  docker/scripts/ld.command.db-import.sh
  docker/scripts/ld.command.db-restore.sh
Labels: documentation

#125 Increase upload file size limit w/ nginx
  docker/build/nginx/conf.d/default.conf
Labels: enhancement

#126 Fix "bad substitution" in db-import -script
  docker/scripts/ld.command.db-import.sh
Labels: bug

#128 Fix datestamp builder
  docker/scripts/ld.command.db-backup.sh
  docker/scripts/ld.command.db-dump.sh
  docker/scripts/ld.command.rebuild.sh
Labels: bug

#133 Issue 132 install drush drupal console with templates
  docker/scripts/ld.command.init.sh
Labels: bug, enhancement

#129 Added gem installation issue and solution
  README.md
Labels: documentation

#136 Issue 124 add php 73
  .env.example
  docker/build/php/7.3/Dockerfile
  docker/build/php/7.3/bash/bashrc
  docker/build/php/7.3/conf.d/90-mailhog.ini
  docker/build/php/7.3/conf.d/95-drupal-development.ini
  docker/docker-compose.common.yml
  docker/docker-compose.nfs.yml
  docker/docker-compose.skeleton.yml
  docker/scripts/ld.command.init.sh
Labels: enhancement
