Repository Exove/local-docker, pull requests merged in 2020-07, with the labels that each got.

#182 #148: Distinguish between non-initialized and initialized projects in the README.
  README.md
Labels: documentation

#188 Add instructions to allow configurations w/o password
  README.md
Labels: documentation, enhancement

#171 Improve docker sync regarding themes
  docker/docker-sync.common.yml
  docker/docker-sync.skeleton.yml
Labels: enhancement
